import { createGlobalTheme } from "@vanilla-extract/css";

export const typography = createGlobalTheme(":root", {
  display1: {
    fontSize: "4rem",
    lineHeight: "5.2rem",
    letterSpacing: "-0.0282em",
    fontWeight: "700",
  },
  display2: {
    fontSize: "3.6rem",
    lineHeight: "4.8rem",
    letterSpacing: "-0.027em",
    fontWeight: "700",
  },
  display3: {
    fontSize: "3.2rem",
    lineHeight: "4.2rem",
    letterSpacing: "-0.025em",
    fontWeight: "700",
  },
  title1Bd: {
    fontSize: "2.4rem",
    lineHeight: "3.2rem",
    letterSpacing: "-0.023em",
    fontWeight: "700",
  },
  title1Md: {
    fontSize: "2.4rem",
    lineHeight: "3.2rem",
    letterSpacing: "-0.023em",
    fontWeight: "500",
  },
  title1Rg: {
    fontSize: "2.4rem",
    lineHeight: "3.2rem",
    letterSpacing: "-0.023em",
    fontWeight: "400",
  },
  title2Bd: {
    fontSize: "2rem",
    lineHeight: "2.8rem",
    letterSpacing: "-0.012em",
    fontWeight: "700",
  },
  title2Sb: {
    fontSize: "2rem",
    lineHeight: "2.8rem",
    letterSpacing: "-0.012em",
    fontWeight: "600",
  },
  title2Md: {
    fontSize: "2rem",
    lineHeight: "2.8rem",
    letterSpacing: "-0.012em",
    fontWeight: "500",
  },
  title2Rg: {
    fontSize: "2rem",
    lineHeight: "2.8rem",
    letterSpacing: "-0.012em",
    fontWeight: "400",
  },
  title3Sb: {
    fontSize: "1.8rem",
    lineHeight: "2.6rem",
    letterSpacing: "-0.002em",
    fontWeight: "600",
  },
  title3Md: {
    fontSize: "1.8rem",
    lineHeight: "2.6rem",
    letterSpacing: "-0.002em",
    fontWeight: "500",
  },
  title3Rg: {
    fontSize: "1.8rem",
    lineHeight: "2.6rem",
    letterSpacing: "-0.002em",
    fontWeight: "400",
  },
  body1Sb: {
    fontSize: "1.6rem",
    lineHeight: "2.4rem",
    letterSpacing: "0.0057em",
    fontWeight: "600",
  },
  body1Md: {
    fontSize: "1.6rem",
    lineHeight: "2.4rem",
    letterSpacing: "0.0057em",
    fontWeight: "500",
  },
  body1Rg: {
    fontSize: "1.6rem",
    lineHeight: "2.4rem",
    letterSpacing: "0.0057em",
    fontWeight: "400",
  },
  body2Sb: {
    fontSize: "1.5rem",
    lineHeight: "2.2rem",
    letterSpacing: "0.0096em",
    fontWeight: "600",
  },
  body2Md: {
    fontSize: "1.5rem",
    lineHeight: "2.2rem",
    letterSpacing: "0.0096em",
    fontWeight: "500",
  },
  body2Rg: {
    fontSize: "1.5rem",
    lineHeight: "2.2rem",
    letterSpacing: "0.0096em",
    fontWeight: "400",
  },
  label1Sb: {
    fontSize: "1.4rem",
    lineHeight: "2rem",
    letterSpacing: "0.0145em",
    fontWeight: "600",
  },
  label1Md: {
    fontSize: "1.4rem",
    lineHeight: "2rem",
    letterSpacing: "0.0145em",
    fontWeight: "500",
  },
  label1Rg: {
    fontSize: "1.4rem",
    lineHeight: "2rem",
    letterSpacing: "0.0145em",
    fontWeight: "400",
  },
  label2Sb: {
    fontSize: "1.3rem",
    lineHeight: "1.8rem",
    letterSpacing: "0.0194em",
    fontWeight: "600",
  },
  label2Md: {
    fontSize: "1.3rem",
    lineHeight: "1.8rem",
    letterSpacing: "0.0194em",
    fontWeight: "500",
  },
  label2Rg: {
    fontSize: "1.3rem",
    lineHeight: "1.8rem",
    letterSpacing: "0.0194em",
    fontWeight: "400",
  },
  caption1Sb: {
    fontSize: "1.2rem",
    lineHeight: "1.6rem",
    letterSpacing: "0.0252em",
    fontWeight: "600",
  },
  caption1Md: {
    fontSize: "1.2rem",
    lineHeight: "1.6rem",
    letterSpacing: "0.0252em",
    fontWeight: "500",
  },
  caption1Rg: {
    fontSize: "1.2rem",
    lineHeight: "1.6rem",
    letterSpacing: "0.0252em",
    fontWeight: "400",
  },
  caption2Sb: {
    fontSize: "1.1rem",
    lineHeight: "1.4rem",
    letterSpacing: "0.0311em",
    fontWeight: "600",
  },
  caption2Md: {
    fontSize: "1.1rem",
    lineHeight: "1.4rem",
    letterSpacing: "0.0311em",
    fontWeight: "500",
  },
});
